### ISSUE TITLE
Feature request: out-of-the-box support for deploying private Docker repositories to kubesail

### ISSUE THREAD

**Issue by xaroth8088** [kubesail/deploy-to-kube#21]
As it stands, the default configuration only seems to work if the Docker repository is public.  When it's private, additional configuration is required to create and use the secrets, and these configuration steps are non-obvious.

Ideally, the initial setup should ask for docker hub credentials with a note about how public repos don't require a password to be entered.

**Comment by erulabs** [comment]
Yes - this absolutely needs some love. Will take a look at this shortly. Thanks for the request!

**Comment by erulabs** [comment]
There are a few plans here:

1) Absolutely, the CLI should be more helpful for prompting for private registry auth and generating Kubernetes pull secrets + Secret object / docker-compose setup.

2) We're gearing up to release our own KubeSail powered free image registry - this will be a suggested default in the future to allow people to use `deploy-node-app` properly (ie: without exposing their private image) without having to pay Docker. This should make the "default path" a bit more straight forward.

3) I believe we held off on this because our original intention was to make use of the GitHub artifact registry - unfortunately this is still in beta last I checked - but ideally, if a user has `git` credentials and the repo `deploy-node-app` is being called in has the artifact registry setup, then no prompts are required and the Docker image can be safely stored on GitHub (private or public being unimportant at that point).

I'll look into the state of the GitHub registry, but most likely I'll patch the tool to satisfy #1 while we work on #2 and #3 concurrently.

**Comment by xaroth8088** [comment]
That's awesome!  Thanks for the detailed response.  😄 

If #1 proves painful and/or is moved down on the to-do list, some light documentation on what to do in the meantime could be a helpful bridge until something better is ready for prime-time (like #2).  Alas, I haven't been able to get things working myself or else I'd happily write up those docs for you.  😉

**Comment by erulabs** [comment]
I've added imagePullSecrets support to deploy-node-app in #22 - hopefully this will make it easier to use private repositories!

**Comment by xaroth8088** [comment]
I've tried it out on the PR branch and everything works like a charm.  Thanks again!

**Comment by erulabs** [comment]
Huray! We've officially released version 1.5 to NPM now, so I'm going to close this comment. Thanks again for the feature request and for the help reviewing it!
