### ISSUE TITLE
The future of Deployment - a Dream Setup

### ISSUE THREAD

**Issue by brillout** [kubesail/deploy-to-kube#30]
From the perspective of a developer, the following would be a dream setup.

I define "environments" where:
- An environment defines the system requirements
- Environments can be run on different machines

I define these environments declaratively with `.env.json` files. For example:

~~~json5
// my-app/backend/.env.json

{
  "name": "backend",
  "dependencies": {
    "python": "^3.7.4",
    "postgresql": "^12.0"
  },
  "devDependencies": { // Dependencies for development
    "git": "^2.7.4"
  },
  "prodDependencies": { // Dependencies for production
    "openssh": "^8.1" // Allow machines to connect to the server
  },
}
~~~

~~~json5
// my-app/frontend/.env.json

{
  "name": "frontend",
  "dependencies": {
    "nodejs": "^12.2.0" // The frontend is a Node.js server
  },
  "devDependencies": {
    "git": "^2.7.4"
  },
  "prodDependencies": {
    "openssh": "^8.1",
    "certbot": "^1.15.0" // To get HTTPS certificate
  },
}
~~~

While developing my app, I run all these environments on my personal machine.

Once I want to deploy, I give you guys a set of repositories and you take care of the rest:
- You search in my repositories for `.env.json` files
- You automatically spin up a new (virtual) machine and run all my environments on this single machine.
- You monitor the machine running my environments and as the load hits the performance limits of the machine, you spin up new machines running my environments and distribute load between these machines.

This is high level and the devil is in the details. To name a few:
- How do you determine what environment to scale up? You'd need to now what process belongs to what environment.
- A stateless process is easy to scale up, but what about a database? The machines running my database need to communicate with each other. Maybe you could provide a `kubesail` library that provides the list of the IP address of all machines running the database so that I can properly configure PostgreSQL? Is a list of IP addresses sufficient to configure PostgreSQL?
- Will `certbot` still work when the frontend is being scaled up to several machines?

But such details are not my point. My point is that, as an open source community, we should all work together towards that dream: we should develop tools that helps us get there.

AFAICT Docker is very far away from that dream. Not only is it far away but it is actually a step in the *wrong* direction: I don't see how Docker contributes to this dream.

On the other hand, Nix (https://github.com/NixOS/nix) gets us *much* closer to the dream.

To set it as a hyperbole; Docker is a devil disguised as an angel that insidiously gets us closer to hell. Nix, on the other hand, is a good Samaritan that shows us the way to heaven. It's Nix that showed me that system requirements can be defined in a declarative way and, for that, I will forever be grateful and appreciative of the Nix community.

Whether or not Nix will be the right tool for you guys, I don't know; that's your job to figure that out. All I want, as a mere developer, is my dream.

Needless to say that if you guys get us to the dream, you're in for a big big winning lottery ticket.

**Comment by erulabs** [comment]
hey @brillout - thanks for feedback! I agree strongly with your dream - but I do think containers and orchestration are better suited to accomplish the dream than a package manager ever will be. Nix is an awesome project, but I've been involved in systems administration issues re: packaging software for the majority of my adult life - and I firmly believe Kubernetes is the way forward. Any software targeting the operating-system (eg: package managers like Nix, Apt, etc or infrastructure tools like Terraform) level of abstraction gets it wrong.

For example, consider the solutions to two of the example problems:

> Maybe you could provide a kubesail library that provides the list of the IP address of all machines running the database so that I can properly configure PostgreSQL?

 With something like Nix (or apt, or yum, or anything that installs packages onto a single computer), it would be our custom tool that somehow discovers or tracks installations. Kubernetes provides a standard for _this exact problem_. Instead of knowing _any_ IP addresses, we can simply define a `Service`, which would make a dns name like `postgres.myapp.cluster.local` available to all apps in the `myapp` namespace.

> Will certbot still work when the frontend is being scaled up to several machines?

The same routing system but into Kubernetes solves this too - for example on KubeSail's shared hosting, your requests are first routed through a fleet of Nginx instances, which do things like handle SSL termination, before handing the request back to the routing system, where the request eventually lands on any one of your multiple copies of your app.

Now... Kubernetes does solve these problems. But, since your dream is the development dream (which we _completely_ see as well, to be clear), it must be said that Kubernetes faces the reverse problems of Nix. Running Kubernetes on one laptop is a lot of weight, usually consuming a ton of CPU by itself - plus, you're running a "one-node" cluster, which sort of defeats the purpose. You also seem to imply with your "git" dependency that the project would have workstation-specific tooling, which Docker / Kubernetes doesn't accomplish easily to say the least.

So, what does the dream look like in a containerized world? Let's step thru how I see it:

- You search in my repositories for .env.json files
We do this with `package.json` currently - determining the service dependency stack based on the packages used (for example, the `redis` driver hints that we need a redis server).

- You automatically spin up a new (virtual) machine and run all my environments on this single machine.
We also do this currently - although not in a development friendly way (ie: its aimed at deployments for qa/production etc.) - a single machine or many is an inconsequential detail.

- You monitor the machine running my environments and as the load hits the performance limits of the machine, you spin up new machines running my environments and distribute load between these machines.
This is a really interesting bit - performance limits aside - I would love to easily hoist my local service requirements to a remote cluster. There is a really cool project by a friend of mine called [Mutagen](https://mutagen.io/) that is working towards this development experience.

Anyways, TLDR: Thank you for your post. We absolutely share the same dream. Kubernetes does solve most of these problems, but it's not very development friendly. This is the core pillar of our startup, KubeSail. I look forward to convincing you of this - but it's a big project - so we're taking small steps forward. In the future, I firmly believe something like Mutagen will be bundled with `deploy-node-app`, so that local development can be outsourced to remote machines (also, so dev and prod can be exact matches! Other features like pair programming on a shared state - lots and lots of wins to get)

**Comment by brillout** [comment]
I'm busy atm but I will reply soon.

**Comment by brillout** [comment]
Yes, Docker is the present and if I'd need to scale up a system today, I'd use Docker. But Docker is not the future.

As a developer, all I want are my dependencies: PostgreSQL, Node.js, etc. I want to *declaratively* list my dependencies. That's it.

It is *your* job to provide a scalable environment with these dependencies. How you do this and how my app is being scaled is *your* problem, not mine. Whether you use Kubernetes or whatever is not my problem and I couldn't care less.

But I don't want to see a single line of Docker configuration in my repository. I don't want to configure *anything*. I'm fed up of being told "Docker is the state of the art and you gotta spend days configuring your Docker setup like everyone else". No. I don't want to spend a single minute on something that doesn't contribute to make my business unique.

Every line of code that doesn't contribute to make my business unique will eventually die. Period.

A Docker configuration doesn't contribute to make my business unique. In 50 years Docker will be dead.

You have a chance to make that future happen earlier, in which case you'll be hugely successful.

I'm closing this as you guys seem to categorically reject my dream.

But, if you happen to understand my vision, and if you are willing to fullfil my dream of zero-config declarative scalable deployments, then I'm more than willing to help in whatever ways I can.

**Comment by erulabs** [comment]
> As a developer, all I want are my dependencies: PostgreSQL, Node.js, etc. I want to declaratively list my dependencies. That's it. 

That's exactly what we're building - ideally, your package.json ought to be enough. The meta-modules system is exactly that!

> It is your job to provide a scalable environment with these dependencies. How you do this and how my app is being scaled is your problem, not mine. Whether you use Kubernetes or whatever is not my problem and I couldn't care less.

That is also exactly what `deploy-node-app` does - you choose either docker-compose or Kubernetes and we'll deploy there. There are lots of other systems we could potentially choose - but ideally this gets users off to the best possible start and with tons of possible options.

> But I don't want to see a single line of Docker configuration in my repository.

We could hide this from people - but no one wants the same things. If you want to add a single binary to your system, you can _easily_ do that with a Dockerfile. We could use a different abstraction, but this one is extremely well known. We could potentially offer an option to use the default Dockerfile without copying it into your repo, but that seems pretty minimal - certainly not a dream killer?

> Every line of code that doesn't contribute to make my business unique will eventually die. Period.

A Dockerfile is a fantastic place to put code that makes your company unique!

> In 50 years Docker will be dead.

Maybe - but artifacts will not.

> I want to declaratively list my dependencies.

My friend, that's what Kubernetes is! You do not need all the complexity, and that's just fine, but some people do. Our meta-modules system exactly allows you to declaratively list dependencies - and the Kubernetes configurations allow limitless potential to build data-center scale applications properly.

I'm sorry you feel we're rejecting your dream. If it helps, ignore the word "Docker" where ever you see it. The important bit is that you can wrap up all your code, included in whatever ecosystem you want, however you want, and run it where ever you want. You might not like Docker for what ever reason, but it's a widely accepted format and extremely useful.

If you want, please feel free to write a PR that patches deploy-node-app and the meta-modules system to know how to provision redis/postgres/etc in other ways.
