### ISSUE TITLE
kubernetes-models-ts

### ISSUE THREAD

**Issue by moltar** [kubesail/deploy-to-kube#32]
Not a bug or a feature per-se. Just want to raise awareness of this great package.

https://github.com/tommy351/kubernetes-models-ts

It has TypeScript interfaces and objects for all Kubernetes objects.

It's part of [kosko](https://github.com/tommy351/kosko), but not tightly integrated and stands well on it's own.

I've been using it and experimenting with it. I think it can go well with this package and we don't have to write YAML and can take advantage of OO inheritance and config via JS code, rather than YAML templating.

If you want, I can share my private repo with you that has some POC WIP code.

**Comment by erulabs** [comment]
Hey, this looks cool! kosko is also interesting - but I have fairly strong opinions that infrastructure should be _data_, and not code. This is a realllllly sticky debate, so I've tried my best to keep it out of `deploy-node-app` - but this is why `deploy-node-app` generates basic Kube config files and drops them into place, rather than trying to do something fancy.

That said, Kosko looks awesome, and it seems easy to use this internally and write out YAML just like we do anyways, but also optionally allow writing out these kosko style files as well.

Aside from using this externally, I do want to re-write DNA at some point in typescript - in which case the ts models will be very helpful!

Feel free to share any code you have! I'll absolutely take a look at Kosko for this project, although I can't make promises if it'll fit into `deploy-node-app` right away. Thanks for the heads up!

edit: I will say, I am a big fan of JavaScript for the entire stack, so I'm hard pressed to dislike Kosko too much without being a big ol' hypocrite! 😄

**Comment by moltar** [comment]
@erulabs sent you an invite to the private repo, I'll create an issue there with some explanation also, let me know when you are done, and i'll remove access. It's WIP POC code, so nothing really sensitive.

**Comment by erulabs** [comment]
Closing for now - although moving our projects to TypeScript (and then using `kubernetes-models-ts`) is for sure on our radar. Unfortunately it'll be a while off before we make progress on that. Thanks for the suggestion though!
